/*  =========================================================================
    dblocks-core - DBLOCKS-CORE wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef DBLOCKS_CORE_LIBRARY_H_INCLUDED
#define DBLOCKS_CORE_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  DBLOCKS-CORE version macros for compile-time API detection

#define DBLOCKS_CORE_VERSION_MAJOR 0
#define DBLOCKS_CORE_VERSION_MINOR 1
#define DBLOCKS_CORE_VERSION_PATCH 0

#define DBLOCKS_CORE_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define DBLOCKS_CORE_VERSION \
    DBLOCKS_CORE_MAKE_VERSION(DBLOCKS_CORE_VERSION_MAJOR, DBLOCKS_CORE_VERSION_MINOR, DBLOCKS_CORE_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBDBLOCKS_CORE_STATIC
#       define DBLOCKS_CORE_EXPORT
#   elif defined LIBDBLOCKS_CORE_EXPORTS
#       define DBLOCKS_CORE_EXPORT __declspec(dllexport)
#   else
#       define DBLOCKS_CORE_EXPORT __declspec(dllimport)
#   endif
#else
#   define DBLOCKS_CORE_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _myclass_t myclass_t;
#define MYCLASS_T_DEFINED
typedef struct _myactor_t myactor_t;
#define MYACTOR_T_DEFINED


//  Public API classes
#include "myclass.h"
#include "myactor.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
